Product:
  type: object
  properties:
    id:
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    slug:
      description: 'Name used in the URL path'
      type: string
      example: white-socks
    name:
      description: 'Displayed product name'
      type: string
      example: 'White socks'
    price:
      description: 'Base price of the product excluding schemas'
      type: number
      example: 10.99
    price_min:
      description: 'Min price after applied all sales'
      type: number
      example: 11.99
    price_max:
      description: 'Max price after applied all sales'
      type: number
      example: 19.99
    price_min_initial:
      description: 'Minimum available product price accounting for schemas'
      type: number
      example: 12.99
    price_max_initial:
      description: 'Maximum available product price accounting for schemas'
      type: number
      example: 20.99
    public:
      description: 'Whether product is not set to be hidden.'
      type: boolean
      example: true
    visible:
      description: 'Whether product is visible due to public setting and set visibility'
      type: boolean
      example: true
    available:
      description: 'Whether all parts for minimum product config are available'
      type: boolean
      example: true
    quantity_step:
      description: 'In what increments can you increase the product quantity'
      type: number
      example: 0.05
    quantity:
      description: 'Product quantity summary'
      type: number
      example: 20
    google_product_category:
      description: 'Google product category identification number'
      type: number
      example: 2271
    vat_rate:
      description: 'Value represent tax value'
      type: number
      example: 23
    shipping_time:
      type: integer
      example: 5
    shipping_date:
      type: string
      format: date-time
      example: '2021-09-13T11:11'
    is_digital:
      description: 'Whether product is digital and not delivered by physical means'
      type: boolean
      example: true
    cover:
      $ref: './Media.yml#/Media'
    tags:
      description: 'Ids of assigned subsets'
      type: array
      items:
        $ref: './Tags.yml#/Tag'
    metadata:
      $ref: './../schemas/Metadata.yml#/Metadata'
    metadata_private:
      $ref: './../schemas/Metadata.yml#/Metadata'
    has_schemas:
      description: 'Does product has any attached schema'
      type: boolean
      example: true

ProductView:
  type: object
  allOf:
    - $ref: '#/Product'
    - properties:
        order:
          type: integer
          example: 8
        user_id:
          type: string
          example: 026bc5f6-8373-4aeb-972e-e78d72a67121
        description_html:
          description: 'HTML formatted text to be displayed as a product description'
          type: string
          example: '<h1>Lorem ipsum dolor sit amet</h1>'
        description_short:
          description: 'Plain text short product description'
          type: string
        items:
          $ref: './Items.yml#/ItemWithRequiredQuantity'
        gallery:
          description: 'Ids of assigned subsets'
          type: array
          items:
            $ref: './Media.yml#/Media'
        schemas:
          description: 'Ids of assigned subsets'
          type: array
          items:
            $ref: './../api.yml#/components/schemas/Schema'
        sets:
          description: 'Ids of assigned subsets'
          type: array
          items:
            $ref: './ProductSets.yml#/ProductSet'
        attributes:
          description: 'Array of assigned attributes'
          type: array
          items:
            $ref: './Attributes.yml#/AttributeProduct'
        seo:
          $ref: './Seo.yml#/SeoView'
        sales:
          description: 'List of all applied sales'
          type: array
          items:
            $ref: './Sales.yml#/Sale'
        availability:
          type: array
          items:
            $ref: './ProductAvailabilities.yml#/ProductAvailability'

ProductIndex:
  type: object
  allOf:
    - $ref: '#/Product'
    - properties:
        attributes:
          description: 'Array of assigned attributes'
          type: array
          items:
            $ref: './Attributes.yml#/AttributeProductList'
