Product:
  properties:
    id:
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    slug:
      description: 'Name used in the URL path'
      type: string
      example: white-socks
    name:
      description: 'Displayed product name'
      type: string
      example: 'White socks'
    price:
      description: 'Base price of the product excluding schemas'
      type: numeric
      example: 10.99
    price_min:
      description: 'Minimum available product price acounting for schemas'
      type: numeric
      example: 12.99
    price_max:
      description: 'Maximum available product price acounting for schemas'
      type: numeric
      example: 20.99
    public:
      description: 'Whether product is not set to be hidden.'
      type: boolean
      example: true
    visible:
      description: 'Whether product is visible due to public setting and set visibility'
      type: boolean
      example: true
    available:
      description: 'Whether all parts for minimum product config are available'
      type: boolean
      example: true
    quantity_step:
      description: 'In what increments can you increase the product quantity'
      type: numeric
      example: 0.05
    cover:
      $ref: './Media.yml#/Media'
    tags:
      description: 'Ids of assigned subsets'
      type: array
      items:
        $ref: './Tags.yml#/Tag'
    items:
      description: 'Ids of assigned items'
      type: array
      items:
        $ref: './Items.yml#/ItemWithRequiredQuantity'
#    type: object

ProductView:
  type: object
  allOf:
    - $ref: '#Product'
    - properties:
        user_id:
          type: string
          example: 026bc5f6-8373-4aeb-972e-e78d72a67121
        original_id:
          type: string
          example: 026bc5f6-8373-4aeb-972e-e78d72a67121
        description_html:
          description: 'HTML formated text to be displayed as a product description'
          type: string
          example: '<h1>Lorem ipsum dolor sit amet</h1>'
        meta_description:
          description: 'Tag stripped and trimmed version of HTML description to use as meta data'
          type: string
          example: 'Lorem ipsum dolor sit amet'
        gallery:
          description: 'Ids of assigned subsets'
          type: array
          items:
            $ref: './Media.yml#Media'
        schemas:
          description: 'Ids of assigned subsets'
          type: array
          items:
            $ref: './../api.yml#/components/schemas/Schema'
        sets:
          description: 'Ids of assigned subsets'
          type: array
          items:
            $ref: './ProductSets.yml#/ProductSet'
        seo:
          $ref: './Seo.yml#/SeoView'
        items:
          $ref: './Items.yml#/ItemWithRequiredQuantity'
