ProductSet:
  properties:
    id:
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    name:
      description: 'Name displayed to the user'
      type: string
      example: AGD
    slug:
      description: 'Name used in the URL path'
      type: string
      example: agd
    public:
      description: 'Whether set is visible to unauthorized users'
      type: boolean
      example: true
    hide_on_index:
      description: 'Whether set products should be hidden from the main page'
      type: boolean
      example: false
    parent_id:
      description: 'Id of set, this set belongs to'
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    children_ids:
      description: 'Ids of assigned subsets'
      type: array
      items:
        type: string
        example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    cover:
      $ref: './../schemas/Media.yml#Media'
  type: object

ProductSetParent:
  properties:
    id:
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    name:
      description: 'Name displayed to the user'
      type: string
      example: AGD
    slug:
      description: 'Name used in the URL path'
      type: string
      example: agd
    public:
      description: 'Whether set should be visible to unauthorized users'
      type: boolean
      example: true
    public_parent:
      description: 'When any parent node is set to private, this setting overrides set visibility'
      type: boolean
      example: true
    hide_on_index:
      description: 'Whether set products should be hidden from the main page'
      type: boolean
      example: false
    description_html:
      description: 'HTML formated text to be displayed as a product set description'
      type: string
      example: '<h1>Lorem ipsum dolor sit amet</h1>'
    cover:
      $ref: './../schemas/Media.yml#Media'
    parent:
      $ref: '#ProductSet'
    children_ids:
      description: 'Ids of assigned subsets'
      type: array
      items:
        type: string
        example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    seo:
      $ref: './Seo.yml#SeoView'
  type: object

ProductSetChildren:
  properties:
    id:
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    name:
      description: 'Name displayed to the user'
      type: string
      example: AGD
    slug:
      description: 'Name used in the URL path'
      type: string
      example: agd
    public:
      description: 'Whether set is visible to unauthorized users'
      type: boolean
      example: true
    hide_on_index:
      description: 'Whether set products should be hidden from the main page'
      type: boolean
      example: false
    parent_id:
      description: 'Id of set, this set belongs to'
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    children:
      type: array
      items:
#        Odwołanie do siebie nie działa poprawnie, chociaż przed rozbiciem na pliki działało
#        $ref: '#ProductSetChildren'
        $ref: '#ProductSetChildrenEmpty'
  type: object

ProductSetParentChildren:
  properties:
    id:
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    name:
      description: 'Name displayed to the user'
      type: string
      example: AGD
    slug:
      description: 'Name used in the URL path'
      type: string
      example: agd
    public:
      description: 'Whether set is visible to unauthorized users'
      type: boolean
      example: true
    public_parent:
      description: 'When any parent node is set to private, this setting overrides set visibility'
      type: boolean
      example: true
    hide_on_index:
      description: 'Whether set products should be hidden from the main page'
      type: boolean
      example: false
    parent:
      $ref: '#ProductSet'
    children:
      description: 'Ids of assigned subsets'
      type: array
      items:
        $ref: '#ProductSetChildren'
  type: object

ProductSetChildrenEmpty:
  properties:
    id:
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    name:
      description: 'Name displayed to the user'
      type: string
      example: AGD
    slug:
      description: 'Name used in the URL path'
      type: string
      example: agd
    public:
      description: 'Whether set is visible to unauthorized users'
      type: boolean
      example: true
    hide_on_index:
      description: 'Whether set products should be hidden from the main page'
      type: boolean
      example: false
    parent_id:
      description: 'Id of set, this set belongs to'
      type: string
      example: 026bc5f6-8373-4aeb-972e-e78d72a67121
    children:
      type: array
      items: []
  type: object
