<?php

/**
 * @OA\RequestBody(
 *   request="OrderCreate",
 *   @OA\JsonContent(
 *     @OA\Property(
 *       property="email",
 *       type="string",
 *       example="admin@example.com",
 *     ),
 *     @OA\Property(
 *       property="shipping_method",
 *       type="integer",
 *     ),
 *     @OA\Property(
 *       property="comment",
 *       type="string",
 *       example="asap plz",
 *     ),
 *     @OA\Property(
 *       property="is_statute_accepted",
 *       type="boolean",
 *     ),
 *     @OA\Property(
 *       property="items",
 *       type="array",
 *       @OA\Items(
 *         type="object",
 *         @OA\Property(
 *           property="product_id",
 *           type="integer",
 *         ),
 *         @OA\Property(
 *           property="qty",
 *           type="float",
 *         ),
 *         @OA\Property(
 *           property="schema_items",
 *           type="array",
 *           @OA\Items(
 *             type="integer"
 *           )
 *         ),
 *         @OA\Property(
 *           property="custom_schemas",
 *           type="array",
 *           @OA\Items(
 *             type="object",
 *             @OA\Property(
 *               property="schema_id",
 *               type="integer",
 *             ),
 *             @OA\Property(
 *               property="value",
 *               type="string",
 *             )
 *           )
 *         ),
 *       )
 *     ),
 *     @OA\Property(
 *       property="delivery_address",
 *       ref="#/components/schemas/Address",
 *     ),
 *     @OA\Property(
 *       property="invoice_address",
 *       ref="#/components/schemas/Address",
 *     )
 *   )
 * )
 */
