Product:
  type: object
  properties:
    name:
      type: string
    slug:
      type: string
    price:
      type: number
    description_html:
      type: string
    public:
      type: boolean
    google_product_category:
      type: integer
    media:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    tags:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    schemas:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    sets:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    seo:
      $ref: './../schemas/Seo.yml#/SeoStore'
    items:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    metadata:
      $ref: './../schemas/Metadata.yml#/Metadata'
    metadata_private:
      $ref: './../schemas/Metadata.yml#/Metadata'

ProductStore:
  content:
    application/json:
      schema:
        required:
          - name
          - slug
          - price
          - public
        allOf:
          - $ref: '#Product'
        properties:
          description_short:
            type: string
          attributes:
            type: array
            items:
              type: string
              description: attribute_id,option_id
              example: 0006c3a0-21af-4485-b7fe-9c42233cf03a,0006c654-21bn-44rt-b7fe-9c4uyji8f03a
        type: object

ProductUpdate:
  content:
    application/json:
      schema:
        required:
          - name
          - slug
          - price
          - public
        allOf:
          - $ref: '#Product'
        type: object
