Product:
  type: object
  properties:
    name:
      type: string
    slug:
      type: string
    price:
      type: number
    public:
      type: boolean
    description_html:
      type: string
    description_short:
      type: string
    quantity_step:
      type: number
    vat_rate:
      type: number
    is_digital:
      description: 'Whether product is digital and not delivered by physical means'
      type: boolean
      example: true
    media:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    tags:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    attributes:
      type: object
      properties:
        0006c3a0-21af-4485-b7fe-9c42233cf03a:
          type: string
          description: 'attribute_id as key and option_id as value'
          example: 0006c654-21bn-44rt-b7fe-9c4uyji8f03a
    items:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
          required_quantity:
            type: number
            example: 2
    schemas:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    sets:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    google_product_category:
      type: integer
    seo:
      $ref: './../schemas/Seo.yml#/SeoStore'

ProductStore:
  content:
    application/json:
      schema:
        required:
          - name
          - slug
          - price
          - public
        allOf:
          - $ref: '#/Product'
        type: object
        properties:
          metadata:
            $ref: './../schemas/Metadata.yml#/Metadata'
          metadata_private:
            $ref: './../schemas/Metadata.yml#/Metadata'

ProductUpdate:
  content:
    application/json:
      schema:
        allOf:
          - $ref: '#/Product'
        type: object
