Product:
  type: object
  properties:
    translations:
      type: object
      properties:
        language-uuid:
          type: object
          properties:
            name:
              type: string
            description_html:
              type: string
            description_short:
              type: string
    published:
      type: array
      description: 'Array of published language ids'
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    slug:
      type: string
    price:
      type: number
    public:
      type: boolean
    media:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    tags:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    schemas:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    sets:
      type: array
      items:
        type: string
        example: 0006c3a0-21af-4485-b7fe-9c42233cf03a
    seo:
      $ref: './../schemas/Seo.yml#SeoStore'

ProductStore:
  content:
    application/json:
      schema:
        required:
          - translations
          - published
          - slug
          - price
          - public
        allOf:
          - $ref: '#Product'
        type: object

ProductUpdate:
  content:
    application/json:
      schema:
        required:
          - slug
          - price
          - public
        allOf:
          - $ref: '#Product'
        type: object
