FROM php:8.3-apache

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -

RUN apt-get update && apt-get install -y \
    libc-client-dev \
    libkrb5-dev \
    libpng-dev \
    libjpeg-dev \
    zlib1g-dev \
    libzip-dev \
    libxml2-dev \
    zip \
    unzip \
    nodejs \
    wget

RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-configure gd --with-jpeg
RUN docker-php-ext-install imap pdo_mysql soap gd

RUN npm install -g @apidevtools/swagger-cli
RUN npm install -g @redocly/cli

RUN wget https://github.com/maglnet/ComposerRequireChecker/releases/latest/download/composer-require-checker.phar \
    -O /usr/bin/composer-require-checker
RUN wget https://phar.phpunit.de/phpcpd.phar \
    -O /usr/bin/phpcpd
RUN wget https://github.com/qossmic/deptrac/releases/latest/download/deptrac.phar \
    -O /usr/bin/deptrac
RUN wget https://github.com/vimeo/psalm/releases/latest/download/psalm.phar \
    -O /usr/bin/psalm
RUN wget https://github.com/composer-unused/composer-unused/releases/latest/download/composer-unused.phar \
    -O /usr/bin/composer-unused
RUN wget http://github.com/ergebnis/composer-normalize/releases/latest/download/composer-normalize.phar \
    -O /usr/bin/composer-normalize

RUN chmod 777 /usr/bin/composer-require-checker \
    /usr/bin/phpcpd \
    /usr/bin/deptrac \
    /usr/bin/psalm \
    /usr/bin/composer-unused \
    /usr/bin/composer-normalize

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN a2enmod rewrite

ENV APACHE_DOCUMENT_ROOT /usr/src/app/public

WORKDIR /usr/src/app

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
