Product:
  type: object
  properties:
    slug:
      type: string
    prices_base:
      type: array
      description: "Needs a price for each currency"
      items:
        type: object
        properties:
          value:
            type: string
            example: "9.99"
          currency:
            type: string
            example: "PLN"
          sales_channel_id:
            type: string
            format: uuid
    public:
      type: boolean
    descriptions:
      type: array
      items:
        type: string
        format: uuid
    quantity_step:
      type: number
    shipping_digital:
      description: "Whether product is digital and not delivered by physical means"
      type: boolean
    purchase_limit_per_user:
      type: number
    media:
      type: array
      items:
        type: string
        format: uuid
    tags:
      type: array
      items:
        type: string
        format: uuid
    attributes:
      type: object
      properties:
        0006c3a0-21af-4485-b7fe-9c42233cf03a:
          type: string
          format: uuid
          description: "attribute_id as key and option_id as value"
    items:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
          required_quantity:
            type: number
            example: 2
    schemas:
      type: array
      items:
        type: string
        format: uuid
    sets:
      type: array
      items:
        type: string
        format: uuid
    related_sets:
      type: array
      items:
        type: string
        format: uuid
    google_product_category:
      type: integer
    seo:
      $ref: "./../schemas/Seo.yml#/SeoStore"
    translations:
      type: array
      description: "Translation table for languages. Array key is language UUID"
      items:
        type: object
        properties:
          name:
            description: "Product name"
            type: string
            example: "Shirt"
          description_html:
            description: "HTML formatted text"
            type: string
            example: "<h1>Lorem ipsum dolor sit amet</h1>"
          description_short:
            type: string
    published:
      type: array
      items:
        type: string
        format: uuid
    sales_channels:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
            description: "Sales Channel UUID"
          availability_status:
            type: string
            enum: ["disabled", "hidden", "public"]

ProductStore:
  content:
    application/json:
      schema:
        required:
          - translations
          - slug
          - prices_base
          - public
          - shipping_digital
        allOf:
          - $ref: "#/Product"
        type: object
        properties:
          id:
            type: string
            format: uuid
          metadata:
            $ref: "./../schemas/Metadata.yml#/Metadata"
          metadata_private:
            $ref: "./../schemas/Metadata.yml#/Metadata"

ProductUpdate:
  content:
    application/json:
      schema:
        allOf:
          - $ref: "#/Product"
        type: object
